openapi: 3.0.3
info:
  title: eCommerceAPI
  version: 1.0.0
paths:
  /api/category/:
    get:
      operationId: api_category_list
      description: A Simple ViewSet to list Categories
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/category"
          description: ""
    post:
      operationId: api_category_create
      description: A Simple ViewSet to list Categories
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/category"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/category"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/category"
        required: true
      security:
        - cookieAuth: []
        - basicAuth: []
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/category"
          description: ""
  /api/category/{name}/:
    get:
      operationId: api_category_retrieve
      description: A Simple ViewSet to list Categories
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/category"
          description: ""
    put:
      operationId: api_category_update
      description: A Simple ViewSet to list Categories
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/category"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/category"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/category"
        required: true
      security:
        - cookieAuth: []
        - basicAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/category"
          description: ""
    patch:
      operationId: api_category_partial_update
      description: A Simple ViewSet to list Categories
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Patchedcategory"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/Patchedcategory"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/Patchedcategory"
      security:
        - cookieAuth: []
        - basicAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/category"
          description: ""
    delete:
      operationId: api_category_destroy
      description: A Simple ViewSet to list Categories
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
      responses:
        "204":
          description: No response body
  /api/catgeory/subcategory/:
    get:
      operationId: api_catgeory_subcategory_list
      description: A Simple ViewSet to Subcategories
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/subCategory"
          description: ""
    post:
      operationId: api_catgeory_subcategory_create
      description: A Simple ViewSet to Subcategories
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/subCategory"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/subCategory"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/subCategory"
        required: true
      security:
        - cookieAuth: []
        - basicAuth: []
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/subCategory"
          description: ""
  /api/catgeory/subcategory/{id}/:
    get:
      operationId: api_catgeory_subcategory_retrieve
      description: A Simple ViewSet to Subcategories
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          description: A UUID string identifying this sub category.
          required: true
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/subCategory"
          description: ""
    put:
      operationId: api_catgeory_subcategory_update
      description: A Simple ViewSet to Subcategories
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          description: A UUID string identifying this sub category.
          required: true
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/subCategory"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/subCategory"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/subCategory"
        required: true
      security:
        - cookieAuth: []
        - basicAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/subCategory"
          description: ""
    patch:
      operationId: api_catgeory_subcategory_partial_update
      description: A Simple ViewSet to Subcategories
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          description: A UUID string identifying this sub category.
          required: true
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchedsubCategory"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/PatchedsubCategory"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/PatchedsubCategory"
      security:
        - cookieAuth: []
        - basicAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/subCategory"
          description: ""
    delete:
      operationId: api_catgeory_subcategory_destroy
      description: A Simple ViewSet to Subcategories
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          description: A UUID string identifying this sub category.
          required: true
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
      responses:
        "204":
          description: No response body
  /api/product/:
    get:
      operationId: api_product_list
      description: A Simple ViewSet to CRUD for Product
      tags:
        - Product
      security:
        - cookieAuth: []
        - basicAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
          description: ""
    post:
      operationId: api_product_create
      description: A Simple ViewSet to CRUD for Product
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/Product"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/Product"
        required: true
      security:
        - cookieAuth: []
        - basicAuth: []
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
          description: ""
  /api/product/{name}/:
    get:
      operationId: api_product_retrieve
      description: A Simple ViewSet to CRUD for Product
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
          description: ""
    put:
      operationId: api_product_update
      description: A Simple ViewSet to CRUD for Product
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/Product"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/Product"
        required: true
      security:
        - cookieAuth: []
        - basicAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
          description: ""
    patch:
      operationId: api_product_partial_update
      description: A Simple ViewSet to CRUD for Product
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchedProduct"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/PatchedProduct"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/PatchedProduct"
      security:
        - cookieAuth: []
        - basicAuth: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
          description: ""
    delete:
      operationId: api_product_destroy
      description: A Simple ViewSet to CRUD for Product
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
      responses:
        "204":
          description: No response body
  /api/schema:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
        - in: query
          name: format
          schema:
            type: string
            enum:
              - json
              - yaml
        - in: query
          name: lang
          schema:
            type: string
            enum:
              - af
              - ar
              - ar-dz
              - ast
              - az
              - be
              - bg
              - bn
              - br
              - bs
              - ca
              - ckb
              - cs
              - cy
              - da
              - de
              - dsb
              - el
              - en
              - en-au
              - en-gb
              - eo
              - es
              - es-ar
              - es-co
              - es-mx
              - es-ni
              - es-ve
              - et
              - eu
              - fa
              - fi
              - fr
              - fy
              - ga
              - gd
              - gl
              - he
              - hi
              - hr
              - hsb
              - hu
              - hy
              - ia
              - id
              - ig
              - io
              - is
              - it
              - ja
              - ka
              - kab
              - kk
              - km
              - kn
              - ko
              - ky
              - lb
              - lt
              - lv
              - mk
              - ml
              - mn
              - mr
              - ms
              - my
              - nb
              - ne
              - nl
              - nn
              - os
              - pa
              - pl
              - pt
              - pt-br
              - ro
              - ru
              - sk
              - sl
              - sq
              - sr
              - sr-latn
              - sv
              - sw
              - ta
              - te
              - tg
              - th
              - tk
              - tr
              - tt
              - udm
              - ug
              - uk
              - ur
              - uz
              - vi
              - zh-hans
              - zh-hant
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        "200":
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ""
components:
  schemas:
    PatchedProduct:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        category:
          allOf:
            - $ref: "#/components/schemas/category"
          readOnly: true
        name:
          type: string
          maxLength: 100
        desc:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        discount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        stock_quantity:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        status:
          $ref: "#/components/schemas/StatusEnum"
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        SubCategory:
          type: string
          format: uuid
    Patchedcategory:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 100
    PatchedsubCategory:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 100
        category:
          allOf:
            - $ref: "#/components/schemas/category"
          readOnly: true
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        category:
          allOf:
            - $ref: "#/components/schemas/category"
          readOnly: true
        name:
          type: string
          maxLength: 100
        desc:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        discount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        stock_quantity:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        status:
          $ref: "#/components/schemas/StatusEnum"
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        SubCategory:
          type: string
          format: uuid
      required:
        - SubCategory
        - category
        - created_at
        - desc
        - id
        - name
        - price
        - stock_quantity
        - updated_at
    StatusEnum:
      enum:
        - active
        - inactive
      type: string
      description: |-
        * `active` - Active
        * `inactive` - Inactive
    category:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 100
      required:
        - id
        - name
    subCategory:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 100
        category:
          allOf:
            - $ref: "#/components/schemas/category"
          readOnly: true
      required:
        - category
        - id
        - name
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
